# Generated by Django 2.2.1 on 2019-05-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='video link')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('query_date', models.DateTimeField(auto_now_add=True, verbose_name='query date')),
            ],
        ),
    ]
